on:
  push:
    tags:
      - "v**"
jobs:
  upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build dependencies
        run: pip install .

      - name: Build
        run: python build.py

      - uses: softprops/action-gh-release@v2
        with:
          files: "nlp-winpython.zip"
